[Main]

# This is the UTC(k) lab name
# It is used to eg extract Circular T data
lab = AUS

# This sets the type of clock used as the flywheel for a UTC(k)
# which determines how Circular T is interpolated and the uncertainty in this
# Clock types are hp5071 std, hp5071 hpt, maser
# clock = hp5071 std

# This is a comma separated list of the GNSS that will be reported
# There must be a corresponding [section] for each GNSS 
# GNSS are BDS, GAL, GLO and GPS
GNSS = GPS

# Size of the window used for averaging CGGTTS, in hours
# The window is centered on UTC0.
# The default value of 2 hours is appropriate for a Cs beam standard
# For a maser, 24 hours is appropriate
# window size = 2

http request = https://webtai.bipm.org/api/v1.0/get-data.html?

# You may need to specify a root certificate if your exit point
# to the Internet is interfering with SSL so that it can inspect traffic. 
# This option will be used with the 'verify' argument to requests.get()
# root certificate =  /usr/local/share/ca-certificates/SomeSelfSignedCert.crt

[Email]
recipients = timelords@gallifrey.org
smtp  server = localhost
sender = timelords@gallifrey.org

[Database]
file  = butcgnss.db

[Report]
# The monthly reports are written here
path = report

header = etc/butcgnss_header.txt
footer = etc/butcgnss_footer.txt

# path to archive of checking files
checking path = report/checking

[RINEX]
# This sets the default path for RINEX navigation files
# You might use this with mixed RINEX 
path = rinex

# Station name
# For V2 styles names, use the four character code eg SYDN
# For V3 style names, use the nine character code  eg SYDN00AUS
station name = SYDN

# RINEX version
version = 3

# The name of this section is defined by main:GNSS
[GPS]

# Path for CGGTTS files
CGGTTS path = cggtts/AU06

# CGGTTS file name prefix and extension are optional, depending on the
# file naming convention in use
# If nothing is specified, then a file name of the form MJD.cctf is assumed

# Prefix of CGGTTS file eg GZLLnn for BIPM-style names 
CGGTTS prefix = GZAU06

# Extension of CGGTTS file
# CGGTTS extension = 

# You can define an alternate path to find a CGGTTS file
# Alternate CGGTTS path = 
# Alternate CGGTTS prefix =
# Alternate CGGTTS extension =

# Accredited uncertainty for UTCk - bUTC_GNSS, in ns
# Uncertainties lower than this will be clamped to this
UTCk uncertainty = 0

# Accredited uncertainty for  UTC - bUTC_GNSS, in ns
UTC uncertainty = 0

[Paths]

# 'root' sets the path for paths and files, when they are not specified as 
# absolute paths (absolute paths are identified with a leading '/') 
# All file/path specifications will be relative to this
# The default is the user's home directory
# root = /home/butcgnss

# Sets the directory for temporary files
# Temporary files are removed at the end of processing, unless running in debugging mode
# tmp = tmp
 
# Sets the default directory for CGGTTS files
# This can be overridden, per GNSS, via "CGGTTS path" - see under [GPS] above
# cggtts = cggtts

# This sets the path for Circular T files, when a local archive of Circular T is used, rather than querying the Web API
# circular t = cirt
