#
#

[Tool]
# Command which is run (no options allowed at present)
Executable = /usr/local/bin/r2cggtts

# Software version
Version = 8.8

[RINEX]

# RINEX version, used for constructing names, but also for some parsing
version = 3

# Directory for observation files
obs directory = data/rinex/PTBB

# Directory for navigation files
nav directory   = data/rinex/nav

# Station name for observation files
obs sta = PTBB00DEU

# Station name for navigation files
# (for V3, mixed navigation files only at present)
nav sta = BRD400DLR

[CGGTTS]
# A comma separated list of sections defining CGGTTS outputs
Outputs = CGGTTS-BDS-P3

# File name convention : BIPM style or plain (MJD.cctf)
naming convention = BIPM

# Two-letter lab code used for creating BIPM-style file names, as per V2E specification
lab id = PT

# Two-letter receiver code used for creating BIPM-style file names, as per V2E specification
# I've made it 06 because Septentrio PolaRx4 is 05 and Septentrio PolaRx2 is 04 ...
receiver id = 13

# This is the usual parameters file needed by r2cggtts
# If this is set to 'auto', a parameter file is constructed automagically
parameter file = etc/PTBB.paramCGGTTS.dat

# Set number of leap seconds
# If auto, then an attempt is made to determine it from a navigation file
# If not set, then the value in 'parameter file' is used 
leap second = auto

[Params]

# None !


[CGGTTS-BDS-P3]

Constellation = BDS

Code = 3B3

# Delay = 0.0 

# Output directory
Directory = data/cggtts/tmp

[Paths]

# Root directory for paths defined in this section
# Default is ~
root = /home/michael/src/UTCk-tools/butcgnss/verification

# Directory in which temporary files are created
# Default is ~/tmp
tmp = tmp

