#
#

[Tool]
# Command which is run (no options allowed at present)
Executable = /usr/local/bin/r2cggtts

# Software version
Version = 8.8

[RINEX]

# RINEX version, used for constructing names, but also for some parsing
version = 3

# Directory for observation files
obs directory = rinex/PTBB

# Directory for navigation files
nav directory   = rinex/nav

# Station name for observation files
obs sta = PTBB00DEU

# Station name for navigation files
# (for V3, mixed navigation files only at present)
nav sta = BRDC00IGS

[CGGTTS]
# A comma separated list of sections defining CGGTTS outputs
Outputs = CGGTTS-GPS-P3,CGGTTS-BDS-P3,CGGTTS-GAL-P3

# File name convention : BIPM style or plain (MJD.cctf)
naming convention = BIPM

# Two-letter lab code used for creating BIPM-style file names, as per V2E specification
lab id = PT

# Two-letter receiver code used for creating BIPM-style file names, as per V2E specification
# I've made it 06 because Septentrio PolaRx4 is 05 and Septentrio PolaRx2 is 04 ...
receiver id = 13

# This is the usual parameters file needed by r2cggtts
# If this is set to 'auto', a parameter file is constructed automagically
parameter file = etc/PTBB.paramCGGTTS.dat

# Set number of leap seconds
# If auto, then an attempt is made to determine it from a navigation file
# If not set, then the value in 'parameter file' is used 
leap second = auto

[Params]

# These are the parameters needed to automatically create paramCGGTTS.dat
# Not functional yet!
rev date = 2020-06-01

rcvr = XXXXX

ch = 768

lab name = NMIA

comments = none

# Antenna co-ordinates
X = 
Y = 
Z = 

ref = UTC(AUS)

calibration reference = none

ant cab delay = 0.0

clock cab delay = 0.0


[CGGTTS-GPS-P3]

Constellation = GPS

Code = L3P

# Delay = 0.0 

# Output directory
Directory = cggtts


[CGGTTS-GAL-P3]

Constellation = GAL

Code = L3E

# Delay = 0.0 

# Output directory
Directory = cggtts

[CGGTTS-BDS-P3]

Constellation = BDS

Code = 3B2

# Delay = 0.0 

# Output directory
Directory = cggtts


[Paths]

# Root directory for paths defined in this section
# Default is ~
root = /home/michael/src/UTCk-tools/butcgnss/verification

# Directory in which temporary files are created
# Default is ~/tmp
tmp = tmp

