[Main]

# This is the UTC(k) lab name
# It is used to eg extract Circular T data
lab = PTB

# This sets the type of clock used as the flywheel for a UTC(k)
# which determines how Circular T is interpolated and the uncertainty in this
# Clock types are hp5071 std, hp5071 hpt, maser
# Note! Even though the clock is a maser, we want to test as if it was a Cs
# to exercise the relevant code.
clock = hp5071 std

# This is a comma separated list of the GNSS that will be reported
# There must be a corresponding [section] for each GNSS 
# GNSS are BDS, GAL, GLO and GPS
GNSS = GPS, GAL

# Size of the window used for averaging CGGTTS, in hours
# The window is centered on UTC0.
# The default value of 2 hours is appropriate for a Cs beam standard
# For a maser, 24 hours is appropriate
window size = 24

http request = https://webtai.bipm.org/api/v1.0/get-data.html?

# You may need to specify a root certificate if your exit point
# to the Internet is interfering with SSL so that it can inspect traffic. 
# This option will be used with the 'verify' argument to requests.get()
# root certificate =  /usr/local/share/ca-certificates/SomeSelfSignedCert.crt

[Email]
recipients = timelords@gallifrey.org
smtp  server = localhost
sender = timelords@gallifrey.org

[Database]
file  = verifications/20260528_initial_verification/butcgnss.db

[Report]
# The monthly reports are written here
path = verifications/20260528_initial_verification

header = etc/butcgnss_header.txt
footer = etc/butcgnss_footer.txt

# path to archive of checking files
checking path = verifications/20260528_initial_verification

[RINEX]
# This sets the default path for RINEX navigation files
# You might use this with mixed RINEX 
path = data/rinex

# Station name
# For V2 styles names, use the four character code eg SYDN
# For V3 style names, use the nine character code  eg SYDN00AUS
station name = BRDC00IGS

# RINEX version
version = 3

[GPS]

# Path for CGGTTS files
CGGTTS path = data/cggtts

# Prefix of CGGTTS file eg GZLLnn for BIPM-style names 
CGGTTS prefix = GZPT13

[GAL]

# Path for CGGTTS files
CGGTTS path = data/cggtts

# Prefix of CGGTTS file eg GZLLnn for BIPM-style names 
CGGTTS prefix = EZPT13

[Paths]

# 'root' sets the path for paths and files, when they are not specified as 
# absolute paths (absolute paths are identified with a leading '/') 
# All file/path specifications will be relative to this
# The default is the user's home directory
root = src/UTCk-tools/butcgnss/verification

# Sets the directory for temporary files
# Temporary files are removed at the end of processing, unless running in debugging mode
tmp = tmp
 
# Sets the default directory for CGGTTS files
# This can be overridden, per GNSS, via "CGGTTS path" - see under [GPS] above
cggtts = data/cggtts

# This sets the path for Circular T files, when a local archive of Circular T is used, rather than querying the Web API
circular t = data/cirt
