[Main]

# History length in  months, default = 12 months
# history = 12
history = 6

# UTC laboratory name (3 letter code), default = AUS
# lab = AUS

# Email report, default = no
# email = yes

# Comma delimited list of email recipients
# email recipients = 

# Directory for PDF reports
# If the path has a leading '/' then it is interpreted as an absolute path, otherwise it is relative to the user's home directory
# report path = reports

# Directory for temporary files
# tmp path = tmp

# Root certificate
# If you are on a corporate network where SSL inspection takes place,
# you may be obliged to accept their root certificate
# This sets the 'verify' option to requests.get()
# So if you set this as an empty string, SSL authentication is ignored
# root certificate =
