[BIPM]
# (REQUIRED) FTP server address
server = 1.2.3.4

# (REQUIRED) Login credentials
user = abcdefgh
password=abcd1234

[Data]
# (REQUIRED) Clock data file prefix
file prefix = CDXY

# (REQUIRED) Local directory containing clock data file uploaded for UTCr
local directory = utc/BIPM/UTCr

# (REQUIRED) Remote (BIPM) directory containing clock data file uploaded for UTCr
remote directory = data/UTCr/xyz/CLOCK

# This is the difference between the current MJD and the most recent upload
# The default value is 1
upload delay = 1

# Directory for temporary files
# Default is ~/tmp
# tmp directory = tmp

[Email]
# Sender address
sender = timelord@gallifrey.gov

# Email recipients, comma-separated
recipients = highcouncil@gallifrey.gov

# Server to send mail to
smtp server = mail.gallifrey.gov

# Use this to add extra information to the report
footer = etc/footer.utcrcheck.txt

