[Main]
history = 90

email recipients = Michael.Wouters@openttp.org
smtp  server = localhost
email sender = Michael.Wouters@openttp.org

# a few paths
# all relative to user's home  at present
reports = reports
log     = logs
control = control
tmp     = tmp

clock data = /mnt/logger3/clocks

# Optional
# This is a text file which whose contents will be printed before the plots
# Useful for giving eg instructions 
footer = etc/utcsteersched.footer.txt

# You may need to specify a root certificate 
# if your exit point to the Internet is interfering with
# SSL traffic so that it can inspect traffic. 
# This option will be used with the 'verify' argument to requests.get()
# root certificate =  /usr/local/share/ca-certificates/SomeSelfSignedCert.crt
